name: perrow_api
description: A web server built using the shelf package.
version: 0.0.1
homepage: https://linkedin.com/in/danielmgawi/

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  args: ^2.1.0
  calc: ^0.2.1
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.1.0
  dotenv: ^3.0.0
  geodesy: ^0.4.0-nullsafety.0
  hex: ^0.2.0
  hive_generator: ^1.0.1
  hive: ^2.0.2
  json_annotation: ^4.0.1
  postgrest: ^0.1.0
  realtime_client: ^0.0.8
  redis_dart: ^0.1.0+4
  sentry: ^5.0.0
  shelf_router: ^1.0.0
  supabase: ^0.0.1-dev.14
  throttling: ^1.0.0
  timeago: ^3.0.2
  uuid: ^3.0.3
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^1.12.2
  build_web_compilers: ^2.12.2
  json_serializable: ^4.1.0
  pedantic: ^1.11.0
  test: ^1.14.4
