name: perrow_api
description: A transaction record keeping server built using the shelf package.
version: 0.1.5
homepage: https://linkedin.com/in/danielmgawi/

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  africas_talking: ^0.0.1
  calc: ^0.2.1
  dart_date: ^1.1.0
  dart_jsonwebtoken: ^2.3.0
  date_time_format: ^2.0.1
  dotenv: ^3.0.0
  enough_mail: ^1.3.4
  enum_to_string: ^2.0.1
  geodesy: ^0.4.0-nullsafety.0
  hex: ^0.2.0
  hive_generator: ^1.0.1
  hive: ^2.0.2
  jiffy: ^4.1.0
  json_annotation: ^4.1.0
  pedantic: ^1.11.1
  postgrest: ^0.1.4
  rate_limiter: ^0.1.1
  realtime_client: ^0.1.4
  retry: ^3.1.0
  sentry: ^6.0.1
  shelf_cors_headers: ^0.1.1
  shelf_router: ^1.0.0
  shelf_secure_cookie: ^1.2.0
  shelf: ^1.1.4
  supabase: ^0.1.0
  throttling: ^1.0.0
  time: ^2.0.0
  uuid: ^3.0.3
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^1.12.2
  build_web_compilers: ^2.12.2
  json_serializable: ^4.1.2
  lints: ^1.0.1
  test: ^1.17.3
