name: perrow_api
description: A web server built using the shelf package.
version: 0.0.1
homepage: https://linkedin.com/in/danielmgawi/

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  args: ^2.1.0
  calc: ^0.2.1
  dart_date: ^1.1.0
  dart_jsonwebtoken: ^2.1.0
  dotenv: ^3.0.0
  enum_to_string: ^2.0.1
  geodesy: ^0.4.0-nullsafety.0
  hex: ^0.2.0
  hive_generator: ^1.0.1
  hive: ^2.0.2
  json_annotation: ^4.0.1
  postgrest: ^0.1.0
  pubnub: ^4.0.0-beta.0
  realtime_client: ^0.0.8
  redis_dart: ^0.1.0+4
  shelf_router: ^1.0.0
  shelf_secure_cookie: ^1.2.0
  shelf: ^1.1.4
  supabase: ^0.0.1-dev.16
  throttling: ^1.0.0
  time: ^2.0.0
  uuid: ^3.0.3
  validators: ^3.0.0
  retry: ^3.1.0
  jiffy: ^4.1.0

dev_dependencies:
  build_runner: ^1.12.2
  build_web_compilers: ^2.12.2
  json_serializable: ^4.1.2
  pedantic: ^1.11.0
  test: ^1.17.3
